Run test_xcode13_uitest_signing if Xcode >= 11.

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -15,11 +15,24 @@ app:
 
 workflows:
   test_xcode13_uitest_signing:
+    before_run:
+      - _expose_xcode_version
     steps:
-      - bitrise-run:
-          inputs:
-            - workflow_id: utility_test_xcode13_uitest_signing
-            - bitrise_config_path: ./e2e/bitrise.yml
+    - script:
+        inputs:
+          - content: |-
+              #!/bin/env bash
+              set -e
+              if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
+                echo "This test case requires Xcode >= 11, skipping..."
+                exit 0
+              fi
+              envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
+    - bitrise-run:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
+        inputs:
+          - workflow_id: utility_test_xcode13_uitest_signing
+          - bitrise_config_path: ./e2e/bitrise.yml
 
   utility_test_xcode13_uitest_signing:
     envs:
@@ -40,9 +53,21 @@ workflows:
       - _check_xcode_build_for_test
 
   test_uitest_signing:
+    before_run:
+      - _expose_xcode_version
     steps:
+    - script:
+        inputs:
+          - content: |-
+              #!/bin/env bash
+              set -e
+              if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
+                echo "This test case requires Xcode >= 11, skipping..."
+                exit 0
+              fi
+              envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
     - bitrise-run:
-        run_if: '{{getenv "BITRISEIO_STACK_ID" | ne "osx-xcode-10.3.x"}}'
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
         inputs:
         - workflow_id: utility_test_uitest_signing
         - bitrise_config_path: ./e2e/bitrise.yml
@@ -303,3 +328,25 @@ workflows:
       - deploy-to-bitrise-io:
           inputs:
             - notify_user_groups: none
+
+  _expose_xcode_version:
+    steps:
+      - script:
+          title: Expose Xcode major version
+          inputs:
+            - content: |-
+                #!/bin/env bash
+                set -e
+                if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
+                  echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
+                  exit 0
+                fi
+                version=`xcodebuild -version`
+                regex="Xcode ([0-9]*)."
+                if [[ ! $version =~ $regex ]]; then
+                  echo "Failed to determine Xcode major version"
+                  exit 1
+                fi
+                xcode_major_version=${BASH_REMATCH[1]}
+                echo "Xcode major version: $xcode_major_version"
+                envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
